### ISSUE TITLE
blocky/config.yml is outdated

### ISSUE THREAD

**Issue by JenswBE** [0xERR0R/blocky-grafana-prometheus-example#1]
Thanks for the great software and handy example!

Unfortunately, after applying this example, I noticed some config variables are deprecated, e.g. `httpPort` => `ports.http`.

Any chance this example could be updated as the [docs still refer to this repo](https://0xerr0r.github.io/blocky/v0.23/prometheus_grafana#grafana-and-prometheus-example-project)?

**Comment by 0xERR0R** [comment]
Yes, this example is outdated. I'll update it

**Comment by 0xERR0R** [comment]
updated for blocky 0.24
